---
name: Release candidate

on:
  workflow_dispatch:
    inputs:
      husarion_ugv_branch:
        description: Branch name of the release candidate.
        type: string
        default: ros2-devel

jobs:
  run_external_action:
    runs-on: ubuntu-22.04
    steps:
      - name: Print info
        run: echo 'Action is running'

      - name: Trigger external repository
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: rafal-gorecki
          repo: action_test
          github_token: ${{ secrets.GH_PAT }}
          workflow_file_name: test-release.yml
          ref: add-workflow-call
          wait_interval: 10
          client_payload: |
            {
              "husarion_ugv_branch": "${{ inputs.husarion_ugv_branch }}"
            }
