---
name: Trigger using workflow_call

on:
  workflow_dispatch:
    inputs:
      husarion_ugv_branch:
        description: Branch name of the release candidate.
        type: string
        default: ros2-devel

jobs:
  run_external_action:
    uses: rafal-gorecki/release-action/.github/workflows/test-release.yml@main
    with:
      husarion_ugv_branch: ${{ github.event.inputs.husarion_ugv_branch }}
